### ISSUE TITLE
graalvm native image generation fails due to logback

### ISSUE THREAD

**Issue by shashanka981** [logfellow/logstash-logback-encoder#713]
**logback version** :  **net.logstash.logback:logstash-logback-encoder:6.3****

We are trying to build a graalvm native image for our application (version of graalvm: 21.3.0)  and during image generation, I am seeing the following error and image generation with this error. 

rror: Classes that should be initialized at run time got initialized during image building:
 net.logstash.logback.Logback11Support was unintentionally initialized at build time. net.logstash.logback.Logback11Support has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=net.logstash.logback.Logback11Support

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 net.logstash.logback.Logback11Support was unintentionally initialized at build time. net.logstash.logback.Logback11Support has been initialized without the native-image initialization instrumentation and the stack trace can't be tracked. Try marking this class for build-time initialization with --initialize-at-build-time=net.logstash.logback.Logback11Support

       at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
       at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:555)
        at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:168)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$12(NativeImageGenerator.java:727)
       at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:73)
       at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:727)
       at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:529)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)

Does logback natively supports graalvm native image support or Is there something that logback library need to fix here or can we safely let this class to initialize during build time as suggested in the error message ?

**Comment by brenuart** [comment]
This class is part of the support of older versions of Logback (1.1.x) and has been removed in logstash-logback-encoder:7.0.
I'm not an expert of Graalvm (at all) and have no idea whether this early initialisation at build time is a problem or not, maybe @philsttr can provide more information. As far as I can tell, it shouldn't be a problem if you are using a recent version of Logback, i.e. you are **NOT** using Logback 1.1.x... In this case, I guess the class will be initialized correctly and the rest of the codebase will not wrongly assume it must adapt itself to an old version of Logback.

If this class is the only warning you get while building your application, I would recommend you upgrade to the latest version of logstash-logback-encoder instead where it has been removed. Whatever happens we are strongly interested in knowing how the project behaves in a Graalvm environment... so please don't hesitate to post any feedback. We'll try to help with any further issue you might encounter.
