### ISSUE TITLE
Unable to send event due to class cast exception - logback version 6.3 on springboot application

### ISSUE THREAD

**Issue by theamith** [logfellow/logstash-logback-encoder#724]
I am trying to send http request headers of spring boot application, but getting below warning while running spring boot application jar. logback encoder version 6.3 is used and list of all jars used by the application is provided below.

```
01:47:46,283 |-WARN in net.logstash.logback.appender.LogstashAccessTcpSocketAppender[access-log] - Log destination localhost:5000: unable to send event: class ch.qos.logback.classic.spi.LoggingEvent cannot be cast to class ch.qos.logback.access.spi.IAccessEvent (ch.qos.logback.classic.spi.LoggingEvent and ch.qos.logback.access.spi.IAccessEvent are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @6267c3bb) Reconnecting. java.lang.ClassCastException: class ch.qos.logback.classic.spi.LoggingEvent cannot be cast to class ch.qos.logback.access.spi.IAccessEvent (ch.qos.logback.classic.spi.LoggingEvent and ch.qos.logback.access.spi.IAccessEvent are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @6267c3bb)
        at java.lang.ClassCastException: class ch.qos.logback.classic.spi.LoggingEvent cannot be cast to class ch.qos.logback.access.spi.IAccessEvent (ch.qos.logback.classic.spi.LoggingEvent and ch.qos.logback.access.spi.IAccessEvent are in unnamed module of loader org.springframework.boot.loader.LaunchedURLClassLoader @6267c3bb)
        at      at net.logstash.logback.composite.accessevent.AccessEventFormattedTimestampJsonProvider.getTimestampAsMillis(AccessEventFormattedTimestampJsonProvider.java:20)
        at      at net.logstash.logback.composite.FormattedTimestampJsonProvider.writeTo(FormattedTimestampJsonProvider.java:149)
        at      at net.logstash.logback.composite.JsonProviders.writeTo(JsonProviders.java:77)
        at      at net.logstash.logback.composite.CompositeJsonFormatter.writeEventToGenerator(CompositeJsonFormatter.java:188)
        at      at net.logstash.logback.composite.CompositeJsonFormatter.writeEventToOutputStream(CompositeJsonFormatter.java:165)
        at      at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:122)
        at      at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:34)
        at      at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.writeEvent(AbstractLogstashTcpSocketAppender.java:600)
        at      at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onEvent(AbstractLogstashTcpSocketAppender.java:562)
        at      at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender$TcpSendingEventHandler.onEvent(AbstractLogstashTcpSocketAppender.java:287)
        at      at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:339)
        at      at net.logstash.logback.appender.AsyncDisruptorAppender$EventClearingEventHandler.onEvent(AsyncDisruptorAppender.java:327)
        at      at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.processEvents(BatchEventProcessor.java:168)
        at      at net.logstash.logback.encoder.com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:125)
        at      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at      at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at      at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at      at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at      at java.base/java.lang.Thread.run(Thread.java:829)
01:47:46,291 |-WARN in net.logstash.logback.appender.LogstashAccessTcpSocketAppender[access-log] - Log destination localhost:5000: Waiting 29960ms before attempting reconnection.
```

logback-spring.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
	<include
		resource="org/springframework/boot/logging/logback/base.xml" />
	<springProperty scope="context" name="application_name"
		source="spring.application.name" />
	<appender name="logstash"
		class="net.logstash.logback.appender.LogstashTcpSocketAppender">
		<destination>localhost:5000</destination>
		<encoder class="net.logstash.logback.encoder.LogstashEncoder" />
	</appender>
	<appender name="access-log"
		class="net.logstash.logback.appender.LogstashAccessTcpSocketAppender">
		<destination>localhost:5000</destination>
		<encoder class="net.logstash.logback.encoder.LogstashAccessEncoder" />
	</appender>
	<root level="INFO">
		<appender-ref ref="logstash" />
		<appender-ref ref="access-log" />
		<appender-ref ref="CONSOLE" />
	</root>
	<logger name="org.springframework" level="INFO" />
</configuration>
```

jars added

```
HdrHistogram-2.1.12.jar                                         mongodb-driver-core-4.0.5.jar
HikariCP-3.4.5.jar                                              mongodb-driver-sync-4.0.5.jar
LatencyUtils-2.0.3.jar                                          netflix-commons-util-0.3.0.jar
accessors-smart-1.2.jar                                         netflix-eventbus-0.3.0.jar
antlr-2.7.7.jar                                                 netflix-infix-0.3.0.jar
antlr-runtime-3.4.jar                                           netflix-statistics-0.1.1.jar
aopalliance-1.0.jar                                             nimbus-jose-jwt-8.19.jar
archaius-core-0.7.6.jar                                         objenesis-2.6.jar
asm-5.0.4.jar                                                   postgresql-42.2.16.jar
aspectjrt-1.9.6.jar                                             reactive-streams-1.0.3.jar
aspectjweaver-1.9.6.jar                                         reactor-core-3.3.10.RELEASE.jar
bcpkix-jdk15on-1.64.jar                                         reactor-extra-3.3.4.RELEASE.jar
bcprov-jdk15on-1.64.jar                                         ribbon-2.3.0.jar
brave-5.12.3.jar                                                ribbon-core-2.3.0.jar
brave-context-slf4j-5.12.3.jar                                  ribbon-eureka-2.3.0.jar
brave-instrumentation-http-5.12.3.jar                           ribbon-httpclient-2.3.0.jar
brave-instrumentation-httpasyncclient-5.12.3.jar                ribbon-loadbalancer-2.3.0.jar
brave-instrumentation-httpclient-5.12.3.jar                     ribbon-transport-2.3.0.jar
brave-instrumentation-jms-5.12.3.jar                            rxjava-1.3.8.jar
brave-instrumentation-kafka-clients-5.12.3.jar                  rxjava-reactive-streams-1.2.1.jar
brave-instrumentation-kafka-streams-5.12.3.jar                  rxnetty-0.4.9.jar
brave-instrumentation-messaging-5.12.3.jar                      rxnetty-contexts-0.4.9.jar
brave-instrumentation-rpc-5.12.3.jar                            rxnetty-servo-0.4.9.jar
brave-instrumentation-servlet-5.12.3.jar                        servo-core-0.12.21.jar
brave-instrumentation-spring-rabbit-5.12.3.jar                  slf4j-api-1.7.30.jar
brave-instrumentation-spring-web-5.12.3.jar                     snakeyaml-1.26.jar
brave-instrumentation-spring-webmvc-5.12.3.jar                  spring-aop-5.2.9.RELEASE.jar
bson-4.0.5.jar                                                  spring-aspects-5.2.9.RELEASE.jar
byte-buddy-1.10.14.jar                                          spring-backend-common-0.0.1-SNAPSHOT.jar
checker-qual-3.5.0.jar                                          spring-beans-5.2.9.RELEASE.jar
classgraph-4.8.44.jar                                           spring-boot-2.3.4.RELEASE.jar
classmate-1.5.1.jar                                             spring-boot-actuator-2.3.4.RELEASE.jar
commons-beanutils-1.9.3.jar                                     spring-boot-actuator-autoconfigure-2.3.4.RELEASE.jar
commons-codec-1.14.jar                                          spring-boot-autoconfigure-2.3.4.RELEASE.jar
commons-collections-3.2.2.jar                                   spring-boot-starter-2.3.4.RELEASE.jar
commons-configuration-1.10.jar                                  spring-boot-starter-actuator-2.3.4.RELEASE.jar
commons-fileupload-1.4.jar                                      spring-boot-starter-aop-2.3.4.RELEASE.jar
commons-io-2.5.jar                                              spring-boot-starter-cache-2.3.4.RELEASE.jar
commons-jxpath-1.3.jar                                          spring-boot-starter-data-jpa-2.3.4.RELEASE.jar
commons-lang-2.6.jar                                            spring-boot-starter-data-mongodb-2.3.4.RELEASE.jar
commons-lang3-3.10.jar                                          spring-boot-starter-jdbc-2.3.4.RELEASE.jar
commons-math-2.2.jar                                            spring-boot-starter-json-2.3.4.RELEASE.jar
cron-utils-9.1.5.jar                                            spring-boot-starter-logging-2.3.4.RELEASE.jar
distributed-lock-api-1.4.2.jar                                  spring-boot-starter-oauth2-resource-server-2.3.4.RELEASE.jar
distributed-lock-core-1.4.2.jar                                 spring-boot-starter-tomcat-2.3.4.RELEASE.jar
dom4j-2.1.3.jar                                                 spring-boot-starter-validation-2.3.4.RELEASE.jar
dozer-core-6.5.0.jar                                            spring-boot-starter-web-2.3.4.RELEASE.jar
error_prone_annotations-2.3.4.jar                               spring-cloud-commons-2.2.5.RELEASE.jar
eureka-client-1.9.25.jar                                        spring-cloud-config-client-2.2.5.RELEASE.jar
eureka-core-1.9.25.jar                                          spring-cloud-context-2.2.5.RELEASE.jar
evictor-1.0.0.jar                                               spring-cloud-loadbalancer-2.2.5.RELEASE.jar
failureaccess-1.0.1.jar                                         spring-cloud-netflix-archaius-2.2.5.RELEASE.jar
feign-core-10.10.1.jar                                          spring-cloud-netflix-eureka-client-2.2.5.RELEASE.jar
feign-form-3.8.0.jar                                            spring-cloud-netflix-hystrix-2.2.5.RELEASE.jar
feign-form-spring-3.8.0.jar                                     spring-cloud-netflix-ribbon-2.2.5.RELEASE.jar
feign-hystrix-10.10.1.jar                                       spring-cloud-openfeign-core-2.2.5.RELEASE.jar
feign-slf4j-10.10.1.jar                                         spring-cloud-sleuth-core-2.2.5.RELEASE.jar
gson-2.8.6.jar                                                  spring-cloud-sleuth-zipkin-2.2.5.RELEASE.jar
guava-29.0-jre.jar                                              spring-cloud-starter-2.2.5.RELEASE.jar
guice-4.1.0.jar                                                 spring-cloud-starter-config-2.2.5.RELEASE.jar
hibernate-commons-annotations-5.1.0.Final.jar                   spring-cloud-starter-loadbalancer-2.2.5.RELEASE.jar
hibernate-core-5.4.21.Final.jar                                 spring-cloud-starter-netflix-archaius-2.2.5.RELEASE.jar
hibernate-types-52-2.10.1.jar                                   spring-cloud-starter-netflix-eureka-client-2.2.5.RELEASE.jar
hibernate-validator-6.1.5.Final.jar                             spring-cloud-starter-netflix-hystrix-2.2.5.RELEASE.jar
httpclient-4.5.12.jar                                           spring-cloud-starter-netflix-ribbon-2.2.5.RELEASE.jar
httpcore-4.4.13.jar                                             spring-cloud-starter-openfeign-2.2.5.RELEASE.jar
hystrix-core-1.5.18.jar                                         spring-cloud-starter-sleuth-2.2.5.RELEASE.jar
hystrix-javanica-1.5.18.jar                                     spring-cloud-starter-zipkin-2.2.5.RELEASE.jar
hystrix-metrics-event-stream-1.5.18.jar                         spring-context-5.2.9.RELEASE.jar
hystrix-serialization-1.5.18.jar                                spring-context-support-5.2.9.RELEASE.jar
istack-commons-runtime-3.0.11.jar                               spring-core-5.2.9.RELEASE.jar
j2objc-annotations-1.3.jar                                      spring-data-commons-2.3.4.RELEASE.jar
jackson-annotations-2.11.2.jar                                  spring-data-jpa-2.3.4.RELEASE.jar
jackson-core-2.11.2.jar                                         spring-data-mongodb-3.0.4.RELEASE.jar
jackson-databind-2.11.2.jar                                     spring-expression-5.2.9.RELEASE.jar
jackson-dataformat-yaml-2.11.2.jar                              spring-jcl-5.2.9.RELEASE.jar
jackson-datatype-jdk8-2.11.2.jar                                spring-jdbc-5.2.9.RELEASE.jar
jackson-datatype-jsr310-2.11.2.jar                              spring-orm-5.2.9.RELEASE.jar
jackson-module-afterburner-2.11.2.jar                           spring-retry-1.2.5.RELEASE.jar
jackson-module-jaxb-annotations-2.11.2.jar                      spring-security-config-5.3.4.RELEASE.jar
jackson-module-parameter-names-2.11.2.jar                       spring-security-core-5.3.4.RELEASE.jar
jakarta.activation-1.2.2.jar                                    spring-security-crypto-5.3.4.RELEASE.jar
jakarta.activation-api-1.2.2.jar                                spring-security-oauth2-core-5.3.4.RELEASE.jar
jakarta.annotation-api-1.3.5.jar                                spring-security-oauth2-jose-5.3.4.RELEASE.jar
jakarta.el-3.0.3.jar                                            spring-security-oauth2-resource-server-5.3.4.RELEASE.jar
jakarta.persistence-api-2.2.3.jar                               spring-security-rsa-1.0.9.RELEASE.jar
jakarta.transaction-api-1.3.3.jar                               spring-security-web-5.3.4.RELEASE.jar
jakarta.validation-api-2.0.2.jar                                spring-tx-5.2.9.RELEASE.jar
jakarta.xml.bind-api-2.3.3.jar                                  spring-web-5.2.9.RELEASE.jar
jandex-2.1.3.Final.jar                                          spring-webmvc-5.2.9.RELEASE.jar
javassist-3.24.0-GA.jar                                         springdoc-openapi-common-1.2.32.jar
javax.activation-api-1.2.0.jar                                  springdoc-openapi-webmvc-core-1.2.32.jar
javax.el-3.0.0.jar                                              stax-api-1.0.1.jar
javax.inject-1.jar                                              stax2-api-4.2.jar
jaxb-api-2.3.1.jar                                              stringtemplate-3.2.1.jar
jaxb-runtime-2.3.3.jar                                          swagger-annotations-2.1.1.jar
jboss-logging-3.4.1.Final.jar                                   swagger-core-2.1.1.jar
jcip-annotations-1.0-1.jar                                      swagger-integration-2.1.1.jar
jcl-over-slf4j-1.7.30.jar                                       swagger-models-2.1.1.jar
jersey-apache-client4-1.19.1.jar                                tomcat-embed-core-9.0.38.jar
jersey-client-1.19.1.jar                                        tomcat-embed-websocket-9.0.38.jar
jersey-core-1.19.1.jar                                          txw2-2.3.3.jar
jettison-1.3.7.jar                                              validation-api-2.0.1.Final.jar
joda-time-2.3.jar                                               woodstox-core-5.3.0.jar
json-smart-2.3.jar                                              xmlpull-1.1.3.1.jar
jsr311-api-1.1.1.jar                                            xpp3_min-1.1.4c.jar
jul-to-slf4j-1.7.30.jar                                         xstream-1.4.11.1.jar
listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar  zipkin-2.21.1.jar
log4j-api-2.13.3.jar                                            zipkin-reporter-2.15.0.jar
log4j-to-slf4j-2.13.3.jar                                       zipkin-reporter-brave-2.15.0.jar
logback-access-1.2.3.jar                                        zipkin-reporter-metrics-micrometer-2.15.0.jar
logback-classic-1.2.3.jar                                       zipkin-sender-activemq-client-2.15.0.jar
logback-core-1.2.3.jar                                          zipkin-sender-amqp-client-2.15.0.jar
logstash-logback-encoder-6.3.jar                                zipkin-sender-kafka-2.15.0.jar
micrometer-core-1.5.5.jar
```

**Comment by brenuart** [comment]
`LogstashTcpSocketAppender` and `LogstashEncoder` are used to serialise standard Logstash `ILoggingEvent` - that is events generated by usual `logger.info(...)` statements.
`LogstashAccessTcpSocketAppender` and `LogstashAccessEncoder` are used to handle `IAccessEvent` events generated by the servlet container (with the help of a LogbackValve for instance in the case of Tomcat.

Your configuration declares two appenders, one for each type of events. However, the ROOT category is mapped to both of them, meaning that any event directed to this category (or one of its child) will be forwarded to **BOTH** appenders. The error you see is caused when logback attempts to transmit an ILoggingEvent to the `LogstashAccessTcpSocketAppender`...

Logback-Access configuration should be defined in a separate configuration file named `logback-access.xml` by default. It creates a distinct logger context that does not share anything with the one initialised by SpringBoot - see [Logback Access](https://logback.qos.ch/access.html) for more information.

Note: I highly recommend you upgrade to a more recent version of logstash-logback-encoder. Newer versions contain a lot of improvements, especially the 7.x series.

**Comment by brenuart** [comment]
@theamith You reacted with a thumbs up... does it mean we can safely close this issue?

**Comment by theamith** [comment]
@brenuart Yes Thankyou. let's do it 👍
