### ISSUE TITLE
When added spring-cloud-starter-oauth2 dependency to the project, an error was reported when the project started 

### ISSUE THREAD

**Issue by nomatterfine** [logfellow/logstash-logback-encoder#725]
**Describe the bug**
When added spring-cloud-starter-oauth2 dependency to the project, an error was reported when the project started 
`ERROR in net.logstash.logback.appender.LogstashTcpSocketAppender[LOGSTASH] - No destination was configured. Use <destination> to add one or more destinations to the appender
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at `
logback.spring.xml
![image](https://user-images.githubusercontent.com/90117583/147184223-f7143ad0-2d19-42e8-87d0-2d3eafa7688a.png)

When <destination>${host}:${port}</destination> is changed to destination>127.0.0.1:5000</destination>，The project can start normally ；

* logstash-logback-encoder 7.0.1
* logback version 1.26
* spring-cloud-starter-oauth2 2.2.4.RELEASE
* java version 1.8
* springboot 2.3.7.RELEASE

**Comment by brenuart** [comment]
When using Spring Cloud, the initialisation of the application is a TWO steps process. Spring Cloud starts with a first small application context containing a few components (the _bootstrap_ application context). This context performs some various additional initialisation tasks before launching the _actual_ context. One of these tasks is fetching the _actual_ application configuration properties from either local application.properties files or remotely from a Config Server.

The bootstrap application context takes its configuration from _bootstrap.properties_ rather than _application.properties_. In a Spring Cloud setup, the LoggingSystem is initialised twice: once for the bootstrap context and a second time for the actual application context. Since your logback configuration relies on external properties loaded by Spring, you should declare them in _bootstrap.properties_ (or disable this bootstrap mechanism).

If you look carefully at your error logs you should see the following ERROR statuses before the final exception stack trace printed by SpringBoot:
```
10:34:22,060 |-ERROR in ch.qos.logback.core.joran.util.PropertySetter@1433046b - Could not invoke method addDestination in class net.logstash.logback.appender.LogstashTcpSocketAppender with parameter of type java.lang.String java.lang.reflect.InvocationTargetException
	at java.lang.reflect.InvocationTargetException
	at 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
...
Caused by: java.lang.IllegalArgumentException: Invalid destination 'host_IS_UNDEFINED:port_IS_UNDEFINED': unparseable value (expected format 'host[:port]').
	at 	at net.logstash.logback.appender.destination.DestinationParser.parse(DestinationParser.java:70)
	at 	at net.logstash.logback.appender.AbstractLogstashTcpSocketAppender.addDestination(AbstractLogstashTcpSocketAppender.java:1142)
	at 	... 54 common frames omitted
```

There you clearly see that the `host` and `port` variables are _undefined_ - this is because they have been declared in _application.properties_ which is not yet loaded at the time logback is configured...

**Comment by nomatterfine** [comment]
Thank you very much for your reply, the problem has been solved
