### ISSUE TITLE
Could not create component [timestamp] of type [null] java.lang.NullPointerException

### ISSUE THREAD

**Issue by cxjava** [logfellow/logstash-logback-encoder#790]
**Describe the bug**

Can't startup in local after upgrade `logstash-logback-encoder` to `7.1`.

**To Reproduce**
1. Use this `logback.xml` configuration...
```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration debug="true">
    <appender class="ch.qos.logback.core.ConsoleAppender" name="STDOUT">
      <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
        <providers>
          <pattern>
            <pattern>
              {
              "log_level": "%level",
              "thread": "%thread",
              "class_name": "%class",
              "line_number": "%line",
              "message": "%message",
              "stack_trace": "%exception{5}",
              "status": "%level"
              }
            </pattern>
          </pattern>
          <timestamp>
            <fieldName>timestamp</fieldName>
            <pattern>[ISO_INSTANT]</pattern>
            <timeZone>UTC</timeZone>
          </timestamp>
        </providers>
      </encoder>
    </appender>
    <root level="INFO">
      <appender-ref ref="STDOUT"/>
    </root>
</configuration>

```
3. Execute this logger statement (e.g. `logger.debug(...)`) ...
4. See error, or unexpected output
```log
22:38:50,626 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
22:38:50,627 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
22:38:50,641 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventJsonProviders] for [providers] property
22:38:50,646 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventPatternJsonProvider] for [pattern] property
22:38:50,653 |-ERROR in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Could not create component [timestamp] of type [null] java.lang.NullPointerException
	at java.lang.NullPointerException
	at 	at net.logstash.logback.composite.FastISOTimestampFormatter$ZoneOffsetState.<init>(FastISOTimestampFormatter.java:186)
	at 	at net.logstash.logback.composite.FastISOTimestampFormatter.<init>(FastISOTimestampFormatter.java:70)
	at 	at net.logstash.logback.composite.FastISOTimestampFormatter.isoOffsetDateTime(FastISOTimestampFormatter.java:99)
	at 	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.createTimestampWriter(AbstractFormattedTimestampJsonProvider.java:198)
	at 	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.updateTimestampWriter(AbstractFormattedTimestampJsonProvider.java:177)
	at 	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.<init>(AbstractFormattedTimestampJsonProvider.java:154)
	at 	at net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider.<init>(LoggingEventFormattedTimestampJsonProvider.java:23)
	at 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at 	at java.base/java.lang.Class.newInstance(Class.java:584)
	at 	at ch.qos.logback.core.joran.util.PropertySetter.isUnequivocallyInstantiable(PropertySetter.java:217)
	at 	at ch.qos.logback.core.joran.util.PropertySetter.getByConcreteType(PropertySetter.java:371)
	at 	at ch.qos.logback.core.joran.util.PropertySetter.getClassNameViaImplicitRules(PropertySetter.java:395)
	at 	at ch.qos.logback.core.joran.action.NestedComplexPropertyIA.begin(NestedComplexPropertyIA.java:106)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:188)
	at 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:165)
	at 	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at 	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at 	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at 	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:282)
	at 	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:240)
	at 	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:216)
	at 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at 	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:339)
	at 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:297)
	at 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164)
	at 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:195)
	at 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:114)
	at 	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:77)
	at 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
	at 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
	at 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
	at 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131)
	at 	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at 	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at 	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at 	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:339)
	at 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:297)
	at 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at 	at Service.main(Service.java:12)
22:38:50,654 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@20:24 - no applicable action for [fieldName], current ElementPath  is [[configuration][appender][encoder][providers][timestamp][fieldName]]
22:38:50,654 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventPatternJsonProvider] for [pattern] property
22:38:50,654 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@22:23 - no applicable action for [timeZone], current ElementPath  is [[configuration][appender][encoder][providers][timestamp][timeZone]]
22:38:50,789 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
22:38:50,789 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@3350ebdd - Propagating INFO level on Logger[ROOT] onto the JUL framework
22:38:50,790 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
22:38:50,790 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
22:38:50,790 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@31e72cbc - Registering current configuration as safe fallback point
```
**Expected behavior**
Start spring boot application successfully

* what output did you expect

Start spring boot application successfully, can see the spring boot banner.

**Additional context**

Using `spring boot 2.6.6`

* logstash-logback-encoder version: `logstash-logback-encoder:7.1`
* logback version: `Gradle: ch.qos.logback:logback-classic:1.2.11 and Gradle: ch.qos.logback:logback-core:1.2.11`
* jackson version: `jackson-core-2.13.2.jar`
* java version: `jdk 11`

**Comment by brenuart** [comment]
Seems to be same issue as PR #789...
