### ISSUE TITLE
timestamp/timeZone not being applied after upgrading to 7.1

### ISSUE THREAD

**Issue by Jojoooo1** [logfellow/logstash-logback-encoder#791]
**Describe the bug**
After upgrading from 7.0.1 to 7.1. using spring boot 2.6.6 (java 17) timezone is not working anymore.

**To Reproduce**
1. Use this `logback.xml` configuration...
```
<springProfile name="kubernetes">
    <appender name="json" class="ch.qos.logback.core.ConsoleAppender">
      <encoder class="net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder">
        <providers>
          <timestamp>
            <timeZone>America/Sao_Paulo</timeZone>
          </timestamp>
          <pattern>
            <pattern>
              {
              "level": "%level",
              "company": "%mdc{company}",
              "message": "%message",
              "traceId": "%mdc{traceId}",
              "spanId": "%mdc{spanId}",
              "requestId": "%mdc{X-Request-ID}",
              "user": "%mdc{user}",
              "logger": "%logger",
              "thread": "%thread"
              }
            </pattern>
          </pattern>
        </providers>
      </encoder>
    </appender>
```
2. look at log timestamp timezone not being applied.

**Expected behavior**
It should respect timestamp zone defined.

**Comment by brenuart** [comment]
The root cause of this issue is similar to #794.

Logback should have failed to initialise properly with the above configuration and a message similar to the following is probably printed on the console:
```
00:45:52,908 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventJsonProviders] for [providers] property
00:45:52,919 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider] for [timestamp] property
00:45:52,922 |-WARN in ch.qos.logback.core.joran.util.PropertySetter@192d74fb - Failed to set property [timeZone] to value "America/Sao_Paulo".  ch.qos.logback.core.util.PropertySetterException: java.lang.reflect.InvocationTargetException
	at ch.qos.logback.core.util.PropertySetterException: java.lang.reflect.InvocationTargetException
	at 	at ch.qos.logback.core.joran.util.PropertySetter.setProperty(PropertySetter.java:133)
	at 	at ch.qos.logback.core.joran.util.PropertySetter.setProperty(PropertySetter.java:98)
	at 	at ch.qos.logback.core.joran.action.NestedBasicPropertyIA.body(NestedBasicPropertyIA.java:95)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBodyAction(Interpreter.java:289)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.characters(Interpreter.java:172)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:57)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.configureByResourceUrl(LogbackLoggingSystem.java:188)
	at 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:165)
	at 	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithConventions(AbstractLoggingSystem.java:80)
	at 	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:60)
	at 	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:132)
	at 	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:313)
	at 	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:282)
...
Caused by: java.lang.reflect.InvocationTargetException
	at 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at 	at ch.qos.logback.core.joran.util.PropertySetter.setProperty(PropertySetter.java:131)
	at 	... 33 common frames omitted
Caused by: java.lang.NullPointerException
	at 	at net.logstash.logback.composite.FastISOTimestampFormatter$ZoneOffsetState.<init>(FastISOTimestampFormatter.java:186)
	at 	at net.logstash.logback.composite.FastISOTimestampFormatter.<init>(FastISOTimestampFormatter.java:70)
	at 	at net.logstash.logback.composite.FastISOTimestampFormatter.isoOffsetDateTime(FastISOTimestampFormatter.java:99)
	at 	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.createTimestampWriter(AbstractFormattedTimestampJsonProvider.java:198)
	at 	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.updateTimestampWriter(AbstractFormattedTimestampJsonProvider.java:177)
	at 	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.setTimeZone(AbstractFormattedTimestampJsonProvider.java:284)
	at 	... 38 common frames omitted
```

The FastISOTimestampFormatter failed to initialise with the `America/Sao_Paulo` time zone and kept using the system default timezone instead.
