### ISSUE TITLE
NullPointerException after upgrade to 7.1

### ISSUE THREAD

**Issue by liaozan** [logfellow/logstash-logback-encoder#792]
* logstash-logback-encoder version : 7.1
* logback version : 1.2.11
* jackson version : 2.3.12
* java version: OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)
* springboot version: 2.6.6
* spring version: 5.3.18
* timezone: Asia/Shanghai
* zoneoffset : +8

here is the stacktrace
```java
java.lang.NullPointerException: null
	at net.logstash.logback.composite.FastISOTimestampFormatter$ZoneOffsetState.<init>(FastISOTimestampFormatter.java:186)
	at net.logstash.logback.composite.FastISOTimestampFormatter.<init>(FastISOTimestampFormatter.java:70)
	at net.logstash.logback.composite.FastISOTimestampFormatter.isoOffsetDateTime(FastISOTimestampFormatter.java:99)
	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.createTimestampWriter(AbstractFormattedTimestampJsonProvider.java:198)
	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.updateTimestampWriter(AbstractFormattedTimestampJsonProvider.java:177)
	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.<init>(AbstractFormattedTimestampJsonProvider.java:154)
	at net.logstash.logback.composite.loggingevent.LoggingEventFormattedTimestampJsonProvider.<init>(LoggingEventFormattedTimestampJsonProvider.java:23)
	at net.logstash.logback.LogstashFormatter.<init>(LogstashFormatter.java:70)
	at net.logstash.logback.LogstashFormatter.<init>(LogstashFormatter.java:104)
	at net.logstash.logback.LogstashFormatter.<init>(LogstashFormatter.java:100)
	at com.schbrain.framework.autoconfigure.logger.logstash.SchbrainLogstashFormatter.<init>(SchbrainLogstashFormatter.java:21)
	at com.schbrain.framework.autoconfigure.logger.logstash.SchbrainLogstashEncoder.createFormatter(SchbrainLogstashEncoder.java:15)
	at net.logstash.logback.encoder.CompositeJsonEncoder.<init>(CompositeJsonEncoder.java:69)
	at net.logstash.logback.encoder.LoggingEventCompositeJsonEncoder.<init>(LoggingEventCompositeJsonEncoder.java:26)
	at net.logstash.logback.encoder.LogstashEncoder.<init>(LogstashEncoder.java:28)
	at com.schbrain.framework.autoconfigure.logger.logstash.SchbrainLogstashEncoder.<init>(SchbrainLogstashEncoder.java:11)
	at com.schbrain.framework.autoconfigure.logger.JsonFormatLoggerAutoConfiguration.createJsonEncoder(JsonFormatLoggerAutoConfiguration.java:145)
	at com.schbrain.framework.autoconfigure.logger.JsonFormatLoggerAutoConfiguration.buildLogstashAppender(JsonFormatLoggerAutoConfiguration.java:123)
	at com.schbrain.framework.autoconfigure.logger.JsonFormatLoggerAutoConfiguration.registerAppender(JsonFormatLoggerAutoConfiguration.java:113)
	at com.schbrain.framework.autoconfigure.logger.JsonFormatLoggerAutoConfiguration.init(JsonFormatLoggerAutoConfiguration.java:88)
	at com.schbrain.framework.autoconfigure.logger.JsonFormatLoggerAutoConfiguration.initialize(JsonFormatLoggerAutoConfiguration.java:81)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:613)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:381)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at com.xxx.Application.main(Application.java:10)
```

**Comment by brenuart** [comment]
See #794 for follow up.
