### ISSUE TITLE
ShortenedThrowableConverter: add option to HIDE elements from generated classes

### ISSUE THREAD

**Issue by brenuart** [logfellow/logstash-logback-encoder#865]
It may come in handy to provide an option to automatically _hide_ stack trace elements originating from generated classes.

For instance:
```
org.sample.SampleException: Unable to process request
	at org.sample.MyController.create(MyControllerController.java:41)
	at org.sample.MyController$$FastClassBySpringCGLIB$$340ae8ef.invoke(<generated>)
...
```
In this example, `MyController$$FastClassBySpringCGLIB$$..` is a CGLIB class generated by Spring at runtime. It gives no additional value to report it in the stacktrace and users may want to remove/hide it to increase visibility.

The converter already allows to exclude elements matching a regex pattern. However a stack element is removed only if it is followed (or preceded) by at least one another excluded item. Also, the excluded items are replaced by a single line reporting the number of exclusions ("... 12 frames excluded").

Here we simply want to silently HIDE elements originating from generated classes so the `exclusion` is not applicable. This feature could leverage the existing `StackElementFilter.withSourceInfo()` filter and would be enabled using a simple flag as follows:
```
<filterGeneratedClasses>true</filterGeneratedClasses>
```

----
Note: how do we detect generated classes?
Is it enough to say that a class is generated if the filename and the line number are unknown? What if the code is compiled without debugging information?

**Comment by brenuart** [comment]
@philsttr What's your opinion ?

**Comment by philsttr** [comment]
I'd rather stick to the regexes.  There are going to be tons of edge cases for generated classes that I do not think logstash-logback-encode should try to detect.  We'll never get it right, and it sounds like a pain to maintain.

We could add another option to the `ShortenedThrowableConverter` to define the exclusion behavior.  Default being the current behavior.  New option for just marking exclusions with an asterisk or something.

something like this:

Original (non-shortened):
```
java.lang.RuntimeException: boom
    at com.foo.A.a()
    at cglib.foo()
    at cglib.bar()
    at com.foo.A.b()
    at java.lang.Thread.run()
```

Existing behavior (with a regex matching cglib.*)

```
java.lang.RuntimeException: boom
    at com.foo.A.a()
    ... 2 frames excluded
    at com.foo.A.b()
    at java.lang.Thread.run()
```

New option for marking where frames were excluded (with a regex matching cglib.*)

```
java.lang.RuntimeException: boom
    at com.foo.A.a()
   *at com.foo.A.b()
    at java.lang.Thread.run()
```
