### ISSUE TITLE
Nullpointer in FastISOTimestampFormatter$ZoneOffsetState.<init> when using custom AsyncAppender

### ISSUE THREAD

**Issue by holymaloney** [logfellow/logstash-logback-encoder#939]
**Describe the bug**
When using a custom AsyncAppender to mask social security numbers from log output together with the LogstashEncoder, logging configuration fails and no logs are written to output

**To Reproduce**
1. Use this `logback.xml` configuration...
```
<configuration>
         <statusListener class="ch.qos.logback.core.status.OnConsoleStatusListener"/>

         <appender name="stdout_json_masked" class="no.nav.common.log.MaskingAppender">
              <appender-ref ref="consoleAppender"/>
         </appender>
    <appender name="consoleAppender" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
    </appender>
   <root level="${ROOT_LOG_LEVEL:-INFO}">
        <appender-ref ref="stdout_json_masked"/>
    </root>
</configuration>
```
With this custom appender:

```
import ch.qos.logback.classic.spi.ILoggingEvent
import ch.qos.logback.classic.spi.IThrowableProxy
import ch.qos.logback.core.AsyncAppenderBase

class MaskingAppender: AsyncAppenderBase<ILoggingEvent>() {
    override fun append(event: ILoggingEvent) {
        super.append(object : ILoggingEvent by event {
            override fun getFormattedMessage(): String? =
                mask(event.formattedMessage)

            override fun getThrowableProxy(): IThrowableProxy? {
                if (event.throwableProxy == null) {
                    return null
                }
                return object : IThrowableProxy by event.throwableProxy {
                    override fun getMessage(): String? =
                        mask(event.throwableProxy.message)
                }
            }

        })
    }

    companion object {
        private val FNR = Regex("""(^|\D)\d{11}(?=$|\D)""")
        fun mask(string: String?): String? {
            return string?.replace(FNR, "$1***********")
        }
    }
}
```

2. Execute this logger statement (e.g. `logger.debug(...)`) ...
3. See error, or unexpected output
First normal status messages:
```
15:47:22,260 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.5
15:47:22,291 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-test.xml] at [file:/Users/hps/IdeaProjects/po-arbeidsoppfolging-meta/dab/veilarbaktivitet/build/resources/test/logback-test.xml]
15:47:22,482 |-INFO in ch.qos.logback.core.model.processor.StatusListenerModelHandler - Added status listener of type [ch.qos.logback.core.status.OnConsoleStatusListener]
15:47:22,510 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [consoleAppender]
15:47:22,511 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:47:24,034 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [stdout_json_masked]
15:47:24,034 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [no.nav.common.log.MaskingAppender]
15:47:24,040 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [consoleAppender] to no.nav.common.log.MaskingAppender[stdout_json_masked]
15:47:24,040 |-INFO in no.nav.common.log.MaskingAppender[stdout_json_masked] - Attaching appender named [consoleAppender] to AsyncAppender.
15:47:24,042 |-INFO in no.nav.common.log.MaskingAppender[stdout_json_masked] - Setting discardingThreshold to 51
15:47:24,043 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
15:47:24,044 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [stdout_json_masked] to Logger[ROOT]
15:47:24,044 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@2120bed - End of configuration.
15:47:24,046 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@5458c71e - Registering current configuration as safe fallback point
```
Then error
```
15:41:05,175 |-ERROR in ch.qos.logback.core.ConsoleAppender[consoleAppender] - Appender [consoleAppender] failed to append. java.lang.NullPointerException: Cannot invoke "java.time.Instant.getEpochSecond()" because "instant" is null
	at java.lang.NullPointerException: Cannot invoke "java.time.Instant.getEpochSecond()" because "instant" is null
	at 	at java.base/java.time.zone.ZoneRules.previousTransition(ZoneRules.java:912)
	at 	at net.logstash.logback.composite.FastISOTimestampFormatter$ZoneOffsetState.<init>(FastISOTimestampFormatter.java:185)
	at 	at net.logstash.logback.composite.FastISOTimestampFormatter.format(FastISOTimestampFormatter.java:93)
	at 	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider$StringFormatterWriter.getTimestampAsString(AbstractFormattedTimestampJsonProvider.java:137)
	at 	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider$StringFormatterWriter.writeTo(AbstractFormattedTimestampJsonProvider.java:132)
	at 	at net.logstash.logback.composite.AbstractFormattedTimestampJsonProvider.writeTo(AbstractFormattedTimestampJsonProvider.java:164)
	at 	at net.logstash.logback.composite.JsonProviders.writeTo(JsonProviders.java:78)
	at 	at net.logstash.logback.composite.AbstractCompositeJsonFormatter.writeEventToGenerator(AbstractCompositeJsonFormatter.java:290)
	at 	at net.logstash.logback.composite.AbstractCompositeJsonFormatter$JsonFormatter.writeEvent(AbstractCompositeJsonFormatter.java:190)
	at 	at net.logstash.logback.composite.AbstractCompositeJsonFormatter.writeEvent(AbstractCompositeJsonFormatter.java:156)
	at 	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:106)
	at 	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:92)
	at 	at net.logstash.logback.encoder.CompositeJsonEncoder.encode(CompositeJsonEncoder.java:36)
	at 	at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:192)
	at 	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:228)
	at 	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
	at 	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:85)
	at 	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at 	at ch.qos.logback.core.AsyncAppenderBase$Worker.run(AsyncAppenderBase.java:302)
```

**Expected behavior**

* what output did you expect

**Additional context**

* logstash-logback-encoder version 7.3
* logback version 1.4.5
* Jackson version 2.14.1
* java version 17

**Comment by brenuart** [comment]
Oh oh... not good. May I ask you with exact JDK you are using and what is your default timezone?

**Comment by holymaloney** [comment]
Sorry, I missed your comment,  @brenuart . It seems our docker images are using temurin 17 LTS version. Our default timezone in Norway is Central European Time CET and Central European Sumer Time CEST (UTC +0100 and UTC +0200)

**Comment by philsttr** [comment]
Hi @holymaloney,

The NPE occurs because  `getInstant()` returns null for the event object that your custom appender passes to `super.append`.

I "fixed" it by overriding `getInstant()` for the event.

```
            override fun getInstant(): Instant {
                return event.instant;
            }
```

Closing since this is not a problem in logstash-logback-encoder.
